version: '3.7'
services:
  api:
    image: skyradio-api
    container_name: skyradio-api
    depends_on:
      - db
    environment:
      - PORT=${PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - SECRET_REFRESH_TOKEN=${SECRET_REFRESH_TOKEN}
  
  db:
    image: mysql:8.1.0
    container_name: skyradio-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}