services:
    api:
      ports:
        - "${PORT}:${PORT}"
      build: 
        context: .
        dockerfile: docker/Dockerfile
      volumes:
        - ./src:/app/src
        - ./.git:/app/.git
        # 
        - ./.vscode:/app/.vscode
        - ./config:/app/config
        - .devcontainer:/app/.devcontainer
        - .env.example:/app/.env.example
        - .gitignore:/app/.gitignore
        - ./docker:/app/docker
        - ./docker-compose.yml:/app/docker-compose.yml
        - ./run.sh:/app/run.sh
        - ./package.json:/app/package.json
        - ./test:/app/test
        # 
        - ..:/workspaces:cached
      command: npm run dev
    
    db:
      ports:
        - 3306:3306