services:
    api:
      environment:
        - NODE_ENV=production

      # Start the API service
      command: npm run start
    
    db:
      ports:
        - 3306:3306
      volumes:
        - ./.db:/var/lib/mysql