networks:
  skyradio-network:
    external: true

services:
    api:
      environment:
        - NODE_ENV=production
      networks:
        - skyradio-network
    
    db:
      ports:
        - 4462:3306
      volumes:
        - ./.db:/var/lib/mysql
        - ./logs:/var/lib/logs
      networks:
        - skyradio-network