networks:
  skyradio-network:
    external: true

services:
    api:
      ports:
        - ${PORT}:3000
      environment:
        - NODE_ENV=production
      networks:
        - skyradio-network
      volumes:
        - ./logs:/app/logs
    
    db:
      ports:
        - 4462:3306
      volumes:
        - ./.db:/var/lib/mysql
      networks:
        - skyradio-network