services:
    api:
      build: !reset null

      environment:
        - NODE_ENV=production

      # Start the API service
      command: npm run start
    
    db:
      volumes:
        - ./.db:/var/lib/mysql