# Stage 1
FROM node:21.6.1-alpine3.19 as builder

WORKDIR /app

COPY package*.json ./

RUN npm install && npm cache clean --force

COPY . .
RUN npm run build
RUN npm prune --production

# Stage 2
FROM node:21.6.1-alpine3.19

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/database ./dist/database
COPY --from=builder /app/package.json ./package.json

CMD ["npm", "start"]