networks:
  skyradio-network:
    external: true

services:
    api:
      environment:
        - NODE_ENV=production
      networks:
        - skyradio-network
    
    db:
      ports:
        - "${DB_PORT}:3306"
      volumes:
        - ./.db:/var/lib/mysql
      networks:
        - skyradio-network