name: Deploy - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_DEPLOY }}
        logout: true
    
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile.prod --tag ghcr.io/carum98/skyradio-api:latest

    - name: Send to registry
      run: docker push ghcr.io/carum98/skyradio-api:latest

  copy-docker-files:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Copy docker-compose.yml
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.yml"
        target: "~/api"

    - name: Copy docker-compose.prod.yml and Dockerfile.prod
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker/docker-compose.prod.yml,docker/Dockerfile.prod"
        target: "~/api/docker"
