name: Deploy - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secret.TOKEN_DEPLOY }}
        logout: true
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/carum98/skyradio-api:$(date +%s)

    - name: Send to registry
      run: docker push ghcr.io/carum98/skyradio-api:$(date +%s)
