name: Deploy - CI

on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/carum98/skyradio-api
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_DEPLOY }}
        logout: true
    
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile.prod --tag ghcr.io/carum98/skyradio-api:${{ steps.meta.outputs.tags }}

    - name: Send to registry
      run: docker push ghcr.io/carum98/skyradio-api:${{ steps.meta.outputs.tags }}

  pull-into-server:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Pull the image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN_DEPLOY }} &&
          docker pull ghcr.io/carum98/skyradio-api:${{ steps.meta.outputs.tags }}

  docker-compose-files:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Copy docker-compose.yml and docker-compose.prod.yml
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.yml,docker/docker-compose.prod.yml"
        target: "~/api"

    - name: Create docker-compose override
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/api &&
          echo -e "services:\n  api:\n    image: ghcr.io/carum98/skyradio-api:${{ steps.meta.outputs.tags }}" > docker-compose.override.yml
