name: Deploy

on:
  push:
    tags:
      - '*.*.*'

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_DEPLOY }}
        logout: true
    
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile.prod --tag ghcr.io/carum98/skyradio-api:${{ github.ref_name }}

    - name: Send to registry
      run: docker push ghcr.io/carum98/skyradio-api:${{ github.ref_name }}

  pull-image:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Pull the image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN_DEPLOY }} &&
          docker pull ghcr.io/carum98/skyradio-api:${{ github.ref_name }}

  docker-compose-files:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Copy docker-compose.yml and docker-compose.prod.yml
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "docker-compose.yml,docker/docker-compose.prod.yml"
        target: "~/api"

    - name: Create docker-compose override
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/api &&
          echo -e "services:\n  api:\n    image: ghcr.io/carum98/skyradio-api:${{ github.ref_name }}" > docker-compose.override.yml

  docker-compose-up:
    runs-on: ubuntu-latest
    needs: [build-and-push, docker-compose-files]
    environment: production

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: SSH into the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/api &&
          # Check if container is running
          if [ "$(docker ps -q -f status=running -f name=skyradio-api)" ]; then
            # Stop the container
            docker stop skyradio-api
          fi &&
          docker compose -f docker-compose.yml -f docker/docker-compose.prod.yml -f docker-compose.override.yml --env-file .env up -d