name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      env:
        PORT: 8080
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        SECRET_REFRESH_TOKEN: ${{ secrets.SECRET_REFRESH_TOKEN }}
      run: |
        echo PORT: '${PORT}'
        ./run.sh --test
   
